name: .NET

on:
  push:
    branches: [ main ]  

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Install AWS Lambda Tools
      run: dotnet tool install -g Amazon.Lambda.Tools 
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::AWS_ACCOUNT_ID:role/ROLE_NAME
        role-session-name: default
    - name: Deploy to AWS Lambda    
      working-directory: ./src
      run:      
        dotnet lambda deploy-serverless   
